# Generated by Django 4.1.13 on 2024-06-05 15:09

import api.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('integration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('deployed', models.BooleanField()),
                ('deployment_date', models.DateTimeField()),
                ('deployment_platform', models.CharField(max_length=100)),
                ('endpoint_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EthicalApproval',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('approved', models.BooleanField()),
                ('approval_id', models.CharField(max_length=100)),
                ('approval_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hyperparameters',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('learning_rate', models.FloatField()),
                ('batch_size', models.IntegerField()),
                ('epochs', models.IntegerField()),
                ('optimizer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('research_interests', djongo.models.fields.JSONField()),
                ('publications', djongo.models.fields.JSONField()),
                ('profile_picture_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=50)),
                ('notifications_enabled', models.BooleanField()),
                ('theme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
                ('profile', djongo.models.fields.EmbeddedField(model_container=api.models.Profile)),
                ('settings', djongo.models.fields.EmbeddedField(model_container=api.models.Settings)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('project_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('collaborators', djongo.models.fields.JSONField()),
                ('status', models.CharField(max_length=50)),
                ('tags', djongo.models.fields.JSONField()),
                ('data_sources', djongo.models.fields.JSONField()),
                ('publications', djongo.models.fields.JSONField()),
                ('ethical_approval', djongo.models.fields.EmbeddedField(model_container=api.models.EthicalApproval)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('model_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('tags', djongo.models.fields.JSONField()),
                ('hyperparameters', djongo.models.fields.EmbeddedField(model_container=api.models.Hyperparameters)),
                ('performance_metrics', djongo.models.fields.EmbeddedField(model_container=api.models.PerformanceMetrics)),
                ('deployment', djongo.models.fields.EmbeddedField(model_container=api.models.Deployment)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.researchproject')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
